### ISSUE TITLE
Using vgg model

### ISSUE THREAD

**Issue by chetankm1992** [dongyp13/Non-Targeted-Adversarial-Attacks#7]
I see you have used resnet and inception model in your code. I just wanted to know how can I use vgg 16 model for adversarial attack as I can see you have model definition in your nets model for vgg. What code I have to update to make it work. Thank you.

**Comment by dongyp13** [comment]
VGG network is different from ResNet and Inception, since it requires input size to be `224*224*3`. And the input pre-processing is also different. If you want to make it work for VGG, you need to change the load_images function 

```
def load_images(input_dir, batch_shape):
  images = np.zeros(batch_shape)
  filenames = []
  idx = 0
  batch_size = batch_shape[0]
  for filepath in tf.gfile.Glob(os.path.join(input_dir, '*.png')):
    with tf.gfile.Open(filepath) as f:
      image = imread(f, mode='RGB')
    image = imresize(image, [FLAGS.image_height, FLAGS.image_width]).astype(np.float)
    image[:,:,0] -= _R_MEAN
    image[:,:,1] -= _G_MEAN
    image[:,:,2] -= _B_MEAN
    images[idx, :, :, :] = image
    filenames.append(os.path.basename(filepath))
    idx += 1
    if idx == batch_size:
      yield filenames, images
      filenames = []
      images = np.zeros(batch_shape)
      idx = 0
  if idx > 0:
    yield filenames, images
```

Note that ``FLAGS.image_height`` and ``FLAGS.image_width`` are 224 instead of 299. Also set 

```
_R_MEAN = 123.68
_G_MEAN = 116.78
_B_MEAN = 103.94
```
